// lang-zh.ts

export const LANG_ES_NAME = 'es';

export const LANG_ES_TRANS = {
     'hello world': 'Hoi wereld',
    'Registreer': 'Registreer',
    'Maand': 'Maand',
    'Prijs': 'Prijs',
    'Omschrijving': 'Omschrijving',
    'Profiel': 'Profiel',
    'Facturen': 'Facturen',
    'Route': 'Route',
    'Uitloggen': 'Uitloggen',
    'Rekening Rijder': 'Rekening Rijder',
    'Profiel gegevens': 'Profiel gegevens',
    'Naam': 'Naam',
    'Achternaam': 'Achternaam',
    'Gebruikernaam': 'Gebruikernaam',
    'Wachtwoord': 'Wachtwoord',
    'Mobiel nummer"': 'Mobiel nummer',
    'PostCode': 'PostCode',
    'Huisnummer': 'Huisnummer',
    'Stad': 'Stad',
    'Profiel wijzigen': 'Profiel wijzigen',
    'Voertuigen': 'Voertuigen',
    'Aanvraag': 'Aanvraag',
    'Aanvragen': 'Aanvragen',
    'Bevestig Wachtwoord': 'Bevestig Wachtwoord',
    'Nieuw account': 'Nieuw account',
    'Bereken afstand voor': 'Bereken afstand voor',
    'Selecteer de datum en het kenten:': 'Selecteer de datum en het kenten:',
    'Datum': 'Datum',
    'Kenteken': 'Kenteken',
    'Van datum': 'Van datum',
    'Tot datum': 'Tot datum',
    'Bereken afstand': 'Bereken afstand',
    'Regio': 'Regio',
    'AfstandType': 'AfstandType',
    'Afstand': 'Afstand',
    'Login': 'Login',
    'Annuleren': 'Annuleren'
};