// lang-en.ts

export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    'hello world': 'hello world',
    'Registreer': 'Register',
    'Maand': 'Month',
    'Prijs': 'Price',
    'Omschrijving': 'Description',
    'Profiel': 'Profile',
    'Facturen': 'Invoices',
    'Route': 'Route',
    'Uitloggen': 'Logout',
    'Rekening Rijder': 'Road pricing',
    'Profiel gegevens': 'Profile information',
    'Naam': 'Name',
    'Achternaam': 'Last name',
    'Gebruikernaam': 'Username',
    'Wachtwoord': 'Password',
    'Mobiel nummer': 'Mobile number',
    'PostCode': 'Zipcode',
    'Huisnummer': 'House number',
    'Stad': 'City',
    'Profiel wijzigen': 'Edit profile',
    'Voertuigen': 'Vehicles',
    'Aanvraag': 'Request',
    'Aanvragen': 'Requests',
    'Bevestig Wachtwoord': 'Repeat password',
    'Nieuw account': 'New account',
    'Bereken afstand voor': 'Calculate distance for',
    'Selecteer de datum en het kenten:': 'Select the date and your licenceplate:',
    'Datum': 'Date',
    'Kenteken': 'Licenceplate',
    'Van datum': 'From date',
    'Tot datum': 'To date',
    'Bereken afstand': 'Calculate distance',
    'Regio': 'Region',
    'AfstandType': 'Distancetype',
    'Afstand': 'Distance',
    'Login': 'Login',
    'Annuleren': 'Cancel',
    'Auto': 'Car',
    'Totaal prijs': 'Total price',
    'Factuur details': 'Invoice details',
    'Betaal status': 'Payment status',
    'Factuur per maand': 'Invoice per month',
    'Niets gevonden voor dit filter': 'Nothing found for this filter',
    'Er is iets mis gegaan': 'Something went terribly wrong',
    'Geen waarde ingevuld': 'No value',
    'Kan deze datums niet uitrekenen': 'Can\'t calculate this dates',
    'Aanvraag kan niet worden voltooid': 'Can\'t complete this request',
    'Kan geen verbinding met de database maken' : 'Can\'t connect to the database'
};